#!/usr/bin/env python3
"""
Script so sánh sơ đồ chân - giúp kiểm tra sơ đồ chân trên PCB module LED
"""

print("=" * 70)
print("SO SÁNH SƠ ĐỒ CHÂN HUB-75E")
print("=" * 70)
print()

print("Sơ đồ chân IDC 16-pin (nhìn từ phía cắm):")
print()
print("     ┌─────────────────┐")
print("     │ 1  3  5  7  9  11 13 15 │  ← Hàng trên")
print("     │ 2  4  6  8  10 12 14 16 │  ← Hàng dưới")
print("     └─────────────────┘")
print("     ↑")
print("  Rãnh định hướng (key)")
print()

print("=" * 70)
print("SƠ ĐỒ CHÂN THEO MAPPING 'REGULAR' (rpi-rgb-led-matrix):")
print("=" * 70)
print()
print("| Chân IDC | Tín hiệu | GPIO | Pin vật lý |")
print("|----------|----------|------|------------|")
print("| 1        | R1       | 13   | 23         |")
print("| 2        | G1       | 19   | 13         |")
print("| 3        | B1       | 26   | 26         |")
print("| 4        | GND      | GND  | -          |")
print("| 5        | R2       | 12   | 24         |")
print("| 6        | G2       | 20   | 21         |")
print("| 7        | B2       | 21   | 19         |")
print("| 8        | E        | 10   | 10         |")
print("| 9        | A        | 15   | 15         |")
print("| 10       | B        | 18   | 16         |")
print("| 11       | C        | 23   | 18         |")
print("| 12       | D        | 25   | 22         |")
print("| 13       | CLK      | 11   | 11         |")
print("| 14       | LAT      | 7    | 7          |")
print("| 15       | OE       | 12   | 12         |")
print("| 16       | GND      | GND  | -          |")
print()
print("✅ Sơ đồ này đã được kiểm tra và xác minh theo sơ đồ chân thực tế")
print("   trên PCB module LED (xem KIEM_TRA_SO_DO_CHAN.md)")
print()

print("=" * 70)
print("KIỂM TRA:")
print("=" * 70)
print()
print("1. Xem sơ đồ chân IN TRÊN PCB CỦA MODULE LED của bạn")
print("   (thường in ở gần cổng IDC)")
print()
print("2. So sánh với sơ đồ trên:")
print("   - Các tín hiệu (R1, G1, B1, R2, G2, B2, A, B, C, D, E, CLK, LAT, OE)")
print("   - Vị trí chân IDC (1-16)")
print()
print("3. Nếu sơ đồ trên PCB KHÁC với sơ đồ trên:")
print("   - Ghi lại sơ đồ chân trên PCB")
print("   - Có thể cần tạo custom hardware mapping")
print()
print("4. Kiểm tra kết nối GPIO thực tế:")
print("   - Đảm bảo các chân GPIO đã kết nối đúng")
print("   - Kiểm tra không có chân nào bị chạm nhau")
print()
print("=" * 70)
print("NẾU SƠ ĐỒ TRÊN PCB KHÁC:")
print("=" * 70)
print()
print("Bạn có thể:")
print("1. Ghi lại sơ đồ chân trên PCB (chân IDC → tín hiệu)")
print("2. So sánh với các hardware mapping có sẵn")
print("3. Hoặc tạo custom hardware mapping trong code")
print()

