#!/bin/bash
echo "=========================================="
echo "KIỂM TRA PHẦN CỨNG LED MATRIX"
echo "=========================================="
echo ""
echo "1. KIỂM TRA NGUỒN ĐIỆN:"
echo "   - Module LED có đèn LED nguồn sáng không?"
echo "   - Nguồn 5V đã được cấp chưa?"
echo "   - Cực tính đúng chưa? (VCC → VCC, GND → GND)"
echo ""
echo "2. KIỂM TRA CÁP DỮ LIỆU:"
echo "   - Cáp IDC 16-pin đã cắm vào cổng DATA_IN chưa?"
echo "   - Cáp đã cắm chắc chắn chưa?"
echo "   - Cáp đã cắm đúng chiều chưa? (có rãnh định hướng)"
echo ""
echo "3. KIỂM TRA GPIO (nếu kết nối trực tiếp):"
echo "   - Các chân GPIO đã kết nối đúng theo sơ đồ chưa?"
echo "   - Xem sơ đồ trong: KET_NOI_HARDWARE.md"
echo ""
echo "4. THỨ TỰ BẬT NGUỒN:"
echo "   - Bật nguồn module LED TRƯỚC"
echo "   - Sau đó mới bật Raspberry Pi"
echo ""
echo "=========================================="
echo "Chạy test với nhiều cấu hình khác nhau:"
echo "  sudo .venv/bin/python3 scripts/test_led_debug.py"
echo "=========================================="
